export default {
  CHANGE_CURRENT_TOKEN: 'CHANGE_CURRENT_TOKEN',
  JSON_RPC_REQUEST: 'JSON_RPC_REQUEST',

  // Response ids
  ICX_BALANCE_REQUEST_ID: 'ICX_BALANCE_REQUEST_ID',
  TOKEN_BALANCE_REQUEST_ID: 'TOKEN_BALANCE_REQUEST_ID',
  DEPOSITED_ICX_BALANCE_REQUEST_ID: 'DEPOSITED_ICX_BALANCE_REQUEST_ID',
  DEPOSITED_TOKEN_BALANCE_REQUEST_ID: 'DEPOSITED_TOKEN_BALANCE_REQUEST_ID',

  BUY_ORDER_REQUEST_ID: 'BUY_ORDER_REQUEST_ID',
  SELL_ORDER_REQUEST_ID: 'SELL_ORDER_REQUEST_ID',

  ICX_DEPOSIT_REQUEST_ID: 'ICX_DEPOSIT_REQUEST_ID',
  TOKEN_DEPOSIT_REQUEST_ID: 'TOKEN_DEPOSIT_REQUEST_ID',
  ICX_WITHDRAW_REQUEST_ID: 'ICX_WITHDRAW_REQUEST_ID',
  TOKEN_WITHDRAW_REQUEST_ID: 'TOKEN_WITHDRAW_REQUEST_ID',

  BUY_REQUEST_ID: 'BUY_REQUEST_ID',
  SELL_REQUEST_ID: 'SELL_REQUEST_ID',
  TRADE_REQUEST_ID: 'TRADE_REQUEST_ID',

  // ICONEX response
  RESPONSE_ADDRESS: 'RESPONSE_ADDRESS',
  RESPONSE_JSON_RPC: 'RESPONSE_JSON-RPC',
  RESPONSE_COMPLETE: 'RESPONSE_COMPLETE',
  ICONEX_RELAY_RESPONSE: 'ICONEX_RELAY_RESPONSE',

  // Request to ICONEX
  LOAD_ADDRESS_REQUEST: 'LOAD_ADDRESS_REQUEST',
  LOAD_ADDRESS_SUCCESS: 'LOAD_ADDRESS_SUCCESS',

  LOAD_BALANCE_REQUEST: 'LOAD_BALANCE_REQUEST',

  LOAD_ICX_BALANCE_REQUEST: 'LOAD_ICX_BALANCE_REQUEST',
  LOAD_ICX_BALANCE_SUCCESS: 'LOAD_ICX_BALANCE_SUCCESS',

  LOAD_TOKEN_BALANCE_REQUEST: 'LOAD_TOKEN_BALANCE_REQUEST',
  LOAD_TOKEN_BALANCE_SUCCESS: 'LOAD_TOKEN_BALANCE_SUCCESS',

  LOAD_DEPOSITED_ICX_BALANCE_REQUEST: 'LOAD_DEPOSITED_ICX_BALANCE_REQUEST',
  LOAD_DEPOSITED_ICX_BALANCE_SUCCESS: 'LOAD_DEPOSITED_ICX_BALANCE_SUCCESS',

  LOAD_DEPOSITED_TOKEN_BALANCE_REQUEST: 'LOAD_DEPOSITED_TOKEN_BALANCE_REQUEST',
  LOAD_DEPOSITED_TOKEN_BALANCE_SUCCESS: 'LOAD_DEPOSITED_TOKEN_BALANCE_SUCCESS',

  // Request to server
  LOAD_TOKEN_LIST_REQUEST: 'LOAD_TOKEN_LIST_REQUEST',
  LOAD_TOKEN_LIST_SUCCESS: 'LOAD_TOKEN_LIST_SUCCESS',
  LOAD_TOKEN_LIST_FAILURE: 'LOAD_TOKEN_LIST_FAILURE',

  LOAD_ORDER_LIST_REQUEST: 'LOAD_ORDER_LIST_REQUEST',
  LOAD_ORDER_LIST_SUCCESS: 'LOAD_ORDER_LIST_SUCCESS',
  LOAD_ORDER_LIST_FAILURE: 'LOAD_ORDER_LIST_FAILURE',

  // LOAD_BUY_ORDER_REQUEST: 'LOAD_BUY_ORDER_REQUEST',
  // LOAD_BUY_ORDER_SUCCESS: 'LOAD_BUY_ORDER_SUCCESS',

  // LOAD_SELL_ORDER_REQUEST: 'LOAD_SELL_ORDER_REQUEST',
  // LOAD_SELL_ORDER_SUCCESS: 'LOAD_SELL_ORDER_SUCCESS',

  // Send transaction types
  DEPOSIT_ICX_REQUEST: 'DEPOSIT_ICX_REQUEST',
  DEPOSIT_ICX_SUCCESS: 'DEPOSIT_ICX_SUCCESS',

  DEPOSIT_TOKEN_REQUEST: 'DEPOSIT_TOKEN_REQUEST',
  DEPOSIT_TOKEN_SUCCESS: 'DEPOSIT_TOKEN_SUCCESS',

  WITHDRAW_ICX_REQUEST: 'WITHDRAW_ICX_REQUEST',
  WITHDRAW_ICX_SUCCESS: 'WITHDRAW_ICX_SUCCESS',

  WITHDRAW_TOKEN_REQUEST: 'WITHDRAW_TOKEN_REQUEST',
  WITHDRAW_TOKEN_SUCCESS: 'WITHDRAW_TOKEN_SUCCESS',

  BUY_REQUEST: 'BUY_REQUEST',
  BUY_SUCCESS: 'BUY_SUCCESS',

  SELL_REQUEST: 'SELL_REQUEST',
  SELL_SUCCESS: 'SELL_SUCCESS',

  TRADE_REQUEST: 'TRADE_REQUEST',
  TRADE_SUCCESS: 'TRADE_SUCCESS',
};
