export default {
  SET_SOCKET: 'SET_SOCKET',
  REMOVE_SOCKET: 'REMOVE_SOCKET',
  CHANGE_CURRENT_TOKEN: 'CHANGE_CURRENT_TOKEN',

  // ICONEX request
  JSON_RPC_REQUEST: 'JSON_RPC_REQUEST',

  ICX_DEPOSIT_REQUEST_ID: 'ICX_DEPOSIT_REQUEST_ID',
  ICX_WITHDRAW_REQUEST_ID: 'ICX_WITHDRAW_REQUEST_ID',
  TOKEN_DEPOSIT_REQUEST_ID: 'TOKEN_DEPOSIT_REQUEST_ID',
  TOKEN_WITHDRAW_REQUEST_ID: 'TOKEN_WITHDRAW_REQUEST_ID',

  TRADE_REQUEST_ID: 'TRADE_REQUEST_ID',

  // ICONEX response
  RESPONSE_ADDRESS: 'RESPONSE_ADDRESS',
  RESPONSE_SIGNING: 'RESPONSE_SIGNING',
  RESPONSE_JSON_RPC: 'RESPONSE_JSON-RPC',
  ICONEX_RELAY_RESPONSE: 'ICONEX_RELAY_RESPONSE',

  // Request to ICONEX
  LOAD_ADDRESS_REQUEST: 'LOAD_ADDRESS_REQUEST',
  LOAD_ADDRESS_SUCCESS: 'LOAD_ADDRESS_SUCCESS',

  LOAD_ICX_BALANCE_REQUEST: 'LOAD_ICX_BALANCE_REQUEST',
  LOAD_ICX_BALANCE_SUCCESS: 'LOAD_ICX_BALANCE_SUCCESS',
  LOAD_ICX_BALANCE_FAILURE: 'LOAD_ICX_BALANCE_FAILURE',

  LOAD_TOKEN_BALANCE_REQUEST: 'LOAD_TOKEN_BALANCE_REQUEST',
  LOAD_TOKEN_BALANCE_SUCCESS: 'LOAD_TOKEN_BALANCE_SUCCESS',
  LOAD_TOKEN_BALANCE_FAILURE: 'LOAD_TOKEN_BALANCE_FAILURE',

  // Request to server
  LOAD_TOKEN_LIST_REQUEST: 'LOAD_TOKEN_LIST_REQUEST',
  LOAD_TOKEN_LIST_SUCCESS: 'LOAD_TOKEN_LIST_SUCCESS',
  LOAD_TOKEN_LIST_FAILURE: 'LOAD_TOKEN_LIST_FAILURE',

  MAKE_ORDER_REQUEST: 'MAKE_ORDER_REQUEST',
  MAKE_ORDER_SUCCESS: 'MAKE_ORDER_SUCCESS',
  MAKE_ORDER_FAILURE: 'MAKE_ORDER_FAILURE',

  // After socket response
  BUY_ORDER_LIST_RECEIVED: 'BUY_ORDER_LIST_RECEIVED',
  SELL_ORDER_LIST_RECEIVED: 'SELL_ORDER_LIST_RECEIVED',

  TRADE_LIST_RECEIVED: 'TRADE_LIST_RECEIVED',
  LAST_TRADE_RECEIVED: 'LAST_TRADE_RECEIVED',

  MY_BUY_ORDER_LIST_RECEIVED: 'MY_BUY_ORDER_LIST_RECEIVED',
  MY_SELL_ORDER_LIST_RECEIVED: 'MY_SELL_ORDER_LIST_RECEIVED',

  MY_TRADE_LIST_RECEIVED: 'MY_TRADE_LIST_RECEIVED',

  // Send transaction types
  DEPOSIT_ICX_REQUEST: 'DEPOSIT_ICX_REQUEST',
  DEPOSIT_ICX_SUCCESS: 'DEPOSIT_ICX_SUCCESS',

  DEPOSIT_TOKEN_REQUEST: 'DEPOSIT_TOKEN_REQUEST',
  DEPOSIT_TOKEN_SUCCESS: 'DEPOSIT_TOKEN_SUCCESS',

  WITHDRAW_ICX_REQUEST: 'WITHDRAW_ICX_REQUEST',
  WITHDRAW_ICX_SUCCESS: 'WITHDRAW_ICX_SUCCESS',

  WITHDRAW_TOKEN_REQUEST: 'WITHDRAW_TOKEN_REQUEST',
  WITHDRAW_TOKEN_SUCCESS: 'WITHDRAW_TOKEN_SUCCESS',

  BUY_REQUEST: 'BUY_REQUEST',
  BUY_SUCCESS: 'BUY_SUCCESS',

  SELL_REQUEST: 'SELL_REQUEST',
  SELL_SUCCESS: 'SELL_SUCCESS',

  TRADE_REQUEST: 'TRADE_REQUEST',
  TRADE_SUCCESS: 'TRADE_SUCCESS',

  // TBD
  LOAD_ORDER_LIST_REQUEST: 'LOAD_ORDER_LIST_REQUEST',
  LOAD_ORDER_LIST_SUCCESS: 'LOAD_ORDER_LIST_SUCCESS',
  LOAD_ORDER_LIST_FAILURE: 'LOAD_ORDER_LIST_FAILURE',
};
